### ISSUE TITLE
Unable to Build a Unity project that is contained in a Sub-Folder

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/unity-build#9]
Most Azure Pipeline functions and other Unity based GitHub actions allow you to configure a folder for the ProjectPath for GitHub Actions.

This helps with organisation if GitHub repositories maintain the Unity project in a sub-folder somewhere in the repository, rather than having the Unity project in the root of the repository..

## Requited solution

Allow a "ProjectPath" argument for all project related GitHub Actions to be able to specify the folder for the Unity project

**Comment by StephenHodgson** [comment]
The princess you're looking for is in another castle.

The unity-setup is a required before you use this action.
It sets up the unity version and that's where you can specify the project folder.

```yaml
        # Installs the Unity Editor based on your project version text file
        # sets -> env.UNITY_EDITOR_PATH
        # sets -> env.UNITY_PROJECT_PATH
        # https://github.com/XRTK/unity-setup
      - uses: xrtk/unity-setup@v7.2
        with:
          build-targets: ${{ matrix.build-target }}
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'
```
